// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhjhpwrfwahmmtaxjveq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoamhwd3Jmd2FobW10YXhqdmVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MDg4NTEsImV4cCI6MjA2Nzk4NDg1MX0.CcZHOtIHMin9ZaVgBSlucpIpo8dP_0XxaDa1orRFubA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});